class AttractionSeeder
  ATTRACTION_DATA = [
    {name: "Boston Public Garden", description: "Established in 1837, The Boston Public Garden was the first public botanical garden in America. Boston Parks and Recreation Department grows all the plants used in bedding-out the Public Garden in their greenhouses. Over 80 species of plants are cultivated there for future plantings in the Garden and more than 50 other locations around the city. Due to the wide variety of plants and its romantic setting, the Garden attracts many weddings. The Parks Department maintains the Victorian traditions to the best of their abilities, so you can judge its beauty for yourself. Admire the rich and unusual plants, the Lagoon, the monuments and fountains, and the Swan Boats created and operated for over 100 years by the Paget family.", address: "4 Charles St", city: "Boston", state: "MA", zip: "02116", image_url: "public-garden.jpg", user: User.first},
    {name: "Freedom Trail", description: "The Freedom Trail is a unique collection of museums, churches, meeting houses, burying grounds, parks, a ship, and historic markers that tell the story of the American Revolution and beyond. The Freedom Trail Foundation's most popular tour highlights the revolutionary history that took place at 11 of the 16 official Freedom Trail historic sites. All Freedom Trail tours led by 18th-century costumed guides are excellent for families, school field trips, corporate team building, incentives, and convention activities. These tours can be customized to fit your group's schedule and are available year round.", address: "1 Faneuil Hall Square", city: "Boston", state: "MA", zip: "02109", image_url: "freedom-trail.jpg", user: User.first},
    {name: "New England Aquarium", description: "Watch nearly 90 penguins streak through the water of the penguin exhibit. Go eye-to-eye with graceful sea turtles as they soar among stingrays, eels, and schools of tropical fish in the four-story Giant Ocean Tank. Step outside to marvel at energetic fur seals and sea lions romping in the open-air New Balance Foundation Marine Mammal Center overlooking Boston Harbor. With more than 70 exhibits, the Aquarium is a must-see destination for families, animal lovers, and adventurers alike.", address: "1 Central Wharf", city: "Boston", state: "MA", zip: "02110", image_url: "ne-aquarium.jpg", user: User.first},
    {name: "Museum of Fine Arts", description: "The MFA is one of the most comprehensive art museums in the world. Experience art from ancient Egyptian to contemporary, special exhibitions, and innovative programs. The centerpiece of the MFA's expansion is a spectacular new wing for the Art of the Americas collection, which doubled the number of objects from the collection on view, including several large-scale masterpieces not displayed for decades.", address: "456 Huntington Ave", city: "Boston", state: "MA", zip: "02115", image_url: "mfa.jpg", user: User.first},
    {name: "Isabella Steward Gardner Museum", description: "Isabella Stewart Gardner first welcomed visitors to her museum on New Year's Day, 1903. On that evening guests listened to the music of Bach, Mozart, and Schumann, gazed in wonder at the courtyard full of flowers, and viewed one of the nation's finest collections of art. Today, visitors experience much the same thing. The Gardner Museum has remained essentially unchanged since its founder's death in 1924. Unchanged but certainly not stagnant. Three floors of galleries surround a garden courtyard blooming with life in all seasons. The galleries are filled with paintings, sculpture, tapestries, furniture, and decorative arts from cultures spanning thirty centuries.", address: "25 Evans Way", city: "Boston", state: "MA", zip: "02115", image_url: "gardner.jpg", user: User.first},
    {name: "TD Garden", description: "As New England’s largest sports and entertainment arena, TD Garden is the home of the storied NHL’s Boston Bruins and NBA’s Boston Celtics franchises and hosts over 3.5 million people a year at its world-renowned concerts, sporting events, family shows, wrestling, and ice shows.
Since its opening in 1995, TD Garden has hosted over 200 events a year. In 2014, owner and operator Delaware North invested over $70 million for a comprehensive arena-wide renovation to upgrade the fan experience including redesigned concourses, new concession offerings and upgraded technology.
The award-winning state-of-the-art TD Garden is a year-round, 19,600-seat arena, fully equipped with three private restaurants – Banners Harbor View, Legends and the Level 5 Bistro – 90 executive suites, 1,100 club seats, a multi-million dollar high definition video scoreboard and complete 360-degree LED technology.", address: "100 Legends Way", city: "Boston", state: "MA", zip: "02114", image_url: "td-garden.jpg", user: User.first},
    {name: "Duck Tours", description: "Hop aboard Boston Duck Tours and enjoy a fully narrated, historic tour of Boston in a 'DUCK', a W.W.II style amphibious landing craft that travels on land and water. You'll cruise by all the places that make Boston the birthplace of freedom and a city of firsts. Just when you think you've seen it all, your ConDUCKtor drives the DUCK right into the Charles River for a breathtaking view of the Boston and Cambridge skylines.", address: "4 Copley Pl", city: "Boston", state: "MA", zip: "02116", image_url: "duck-tour.jpg", user: User.first},
    {name: "Harvard Square", description: "Each year, over 8 million men, women and children visit Harvard Square. Visitors come for a variety of reasons; this is a place of history, of books, of ideas, and of learning. It is a place of bookstores and coffee houses, of fine dining and eclectic shopping. It is a place of folk music and old theaters, of Cuban ballet and world-class music, of street-performers and award-winning pizza, of public discourse, and public art. Whatever brings you here, we welcome you and hope you enjoy your stay", address: "18 Brattle St", city: "Boston", state: "MA", zip: "02138", image_url: "harvard-sq.jpg", user: User.first},
    {name: "USS Constitution", description: "Only yards away from “Old Ironsides,” the Museum is a “must see” for everyone visiting Boston, where interactive galleries take adults, families and children of all ages on a 200-year voyage.
		Learn how a wooden hull helped earn the nickname Old Ironsides.
		Discover how “Old Ironsides” has remained undefeated since being launched in 1797.
		Find out how school children contributed pennies to help save “Old Ironsides.”
		See how sailors ate a diet of hardtack and grog, and climbed masts 200 feet in the air.", address: "Bldg 22, Charlestown Navy Yard", city: "Boston", state: "MA", zip: "02127", image_url: "constitution.jpg", user: User.first},
    {name: "Museum of Science", description: "Just imagine getting up close and personal with a 65-million-year-old Triceratops fossil, witnessing an indoor lightning storm in the iconic Theater of Electricity, walking among butterflies, or taking a journey inside the human body!   While you are here, don't miss the opportunity to explore the galaxies in the Charles Hayden Planetarium and take in a larger-than-life immersive and inspiring film in the Mugar Omni Theater, featuring New England's only IMAX® Dome screen. With 700 interactive exhibits, exciting exhibitions, daily presentations, hands-on activities, and live animals, there is something for everyone! Create, experiment, and have fun at the Museum of Science!", address: "1 Science Park", city: "Boston", state: "MA", zip: "02114", image_url: "science-museum.jpg", user: User.first},
    {name: "Fenway Park", description: "Fenway Park is a baseball park located in Boston, Massachusetts near Kenmore Square. Since 1912, it has been the home for the Boston Red Sox, the city's American League baseball team, and since 1953, its only Major League Baseball franchise. It is the oldest ballpark in Major League Baseball. Though generations have come and gone, Fenway Park remains, much like it did the day it opened on April 20, 1912. Come to a game and find out why Fenway Park is 'America's Most Beloved Ballpark.'", address: "4 Yawkey Way", city: "Boston", state: "MA", zip: "02215", image_url: "fenway.jpg", user: User.first},
    {name: "The North End", description: "Boston's lively Italian neighborhood, known as the North End, is one of Boston's oldest, where the silversmith and activist leader Paul Revere lived at the time of the American Revolution. The Paul Revere House, which he bought in 1770 and lived in when he made his famous ride, is the only patriot's home on the Freedom Trail, and is open to tour. You can also climb to the tower of Old North Church, where lanterns were hung in April 1775 to alert Paul Revere that British troops were headed to Lexington to arrest the patriot leaders and confiscate the munitions supplies. The beautiful white interior of the church still retains its historic box pews.
The North End is a favorite spot for tourists for reasons that go well beyond its important historic sights. Although it has changed a bit over the years since it was filled with newly arrived immigrants from Italy, it retains its Italian character and lively flair. You'll find Italian restaurants; cafes; bakeries; and shops fragrant with aromas of cured olives, fresh-roasted coffee, and Italian cheeses.", address: "193 Salem St", city: "Boston", state: "MA", zip: "02113", image_url: "north-end.jpg", user: User.first},
    {name: "Boston Public Library", description: "Established in 1848. Boston Public Library has a Central Library, twenty-four branches, a literacy center, map center, business library, and a website filled with digital content and services. Established in 1848, Boston Public Library has pioneered public library service in America. It was the first publicly supported municipal library in America, the first public library to lend books, the first to have a branch library, and the first to have a children's room. Each year, the Boston Public Library hosts thousands of programs and serves millions of people. All of its programs and exhibitions are free and open to the public.", address: "700 Boylston St", city: "Boston", state: "MA", zip: "02116", image_url: "bpl.jpg", user: User.first},
    {name: "Boston HarborWalk and Cruises", description: "The Boston waterfront has seen many changes since its early beginnings as a colonial shipping port. After a period of decline for much of the 20th century, new life was breathed into the area in the mid-1970s with an ambitious redevelopment plan. Today, this interesting mix of residential and commercial space is connected by HarborWalk, an attractive walkway along the waterfront, with parks, public art, benches, cafés, interpretive signs, and access to several means of exploring the harbor by cruise boat, ferry, or water taxi. A shuttle-boat also runs to the Charlestown Navy Yard.
Although it extends from Charlestown to South Boston - and will expand considerably farther - the part you won't want to miss goes from the North End through the wisteria-draped pergola of Christopher Columbus Waterfront Park, past Commercial Wharf, India Wharf, and Long Wharf, and by Rowes Wharf before curving along the harbor into the vibrant Seaport District to the Institute of Contemporary Art, an art museum dramatically cantilevered above the water. The Boston Tea Party Ship, a replica of one of the original ships from which the Sons of Liberty dumped tea overboard the night of December 16, 1773, offers tours with a participatory reenactment of the event.", address: "255 State St", city: "Boston", state: "MA", zip: "02109", image_url: "harborwalk.jpg", user: User.first},
    {name: "Boston Symphony Orchestra", description: "The Boston Symphony Orchestra gave its inaugural concert in 1881 at Symphony Hall, one of the world's most acoustically perfect concert halls, opened in 1900. Over more than a century of history, its conductors have included greats such as Pierre Monteux, Serge Koussevitzky, Charles Munch, Seiji Ozawa, and James Levine. In addition to its regular symphony season, the hall is home to the Boston Pops Orchestra, which sets an international standard for performances of lighter music. For many visitors, the highlight of a trip is a Pops concert, either in Symphony Hall or at the Hatch Memorial Shell, an Art Deco outdoor music shell on the riverside Esplanade that has become a Boston landmark. The shell hosts a regular program of concerts and other special events, and is especially famous for the Boston Pop's yearly performance of the 1812 Overture on July 4th. Audiences sit on the lawn in front of the shell with views of Cambridge, Back Bay, and Beacon Hill. You can go behind the scenes on a tour of Symphony Hall where you'll hear the history and traditions of the Boston Symphony Orchestra, its musicians and conductors.", address: "301 Massachusetts Avenue", city: "Boston", state: "MA", zip: "02115", image_url: "bso.jpg", user: User.first}
  ]

  def self.seed!
    ATTRACTION_DATA.each do |attraction|
      name = attraction[:name]
      another = Attraction.find_or_initialize_by(name: name)
      another.assign_attributes(attraction)
      another.save!
    end
  end
end
